package com.voidplayer.music.ui.screens.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.voidplayer.music.R

@Composable
fun getAllSearchableSettings(): List<Triple<String, String, String>> {
        return listOf(
                Triple(stringResource(R.string.account), "Account", "settings/account"),
                Triple(stringResource(R.string.action_logout), "Account", "settings/account"),
                Triple(stringResource(R.string.advanced_login), "Account", "settings/account"),
                Triple(stringResource(R.string.album_text), "Content", "settings/content"),
                Triple(stringResource(R.string.app_language), "Content", "settings/content"),
                Triple(stringResource(R.string.appearance), "Appearance", "settings/appearance"),
                Triple(stringResource(R.string.artist_page_settings), "Content", "settings/content"),
                Triple(stringResource(R.string.audio_normalization), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.auto_download_on_like), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.auto_download_on_like_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.backup_restore), "Backup & Restore", "settings/backup_restore"),
                Triple(stringResource(R.string.cache_size_warning_message), "Storage", "settings/storage"),
                Triple(stringResource(R.string.cache_size_warning_title), "Storage", "settings/storage"),
                Triple(stringResource(R.string.clear_song_cache), "Storage", "settings/storage"),
                Triple(stringResource(R.string.clear_song_cache_dialog), "Storage", "settings/storage"),
                Triple(stringResource(R.string.close), "Content", "settings/content"),
                Triple(stringResource(R.string.content), "Content", "settings/content"),
                Triple(stringResource(R.string.content_country), "Content", "settings/content"),
                Triple(stringResource(R.string.content_language), "Content", "settings/content"),
                Triple(stringResource(R.string.crossfade), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_beta_message), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_beta_title), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_duration), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_gapless), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.crossfade_gapless_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.downloaded_songs), "Storage", "settings/storage"),
                Triple(stringResource(R.string.enable_dynamic_theme), "Appearance", "settings/appearance"),
                Triple(stringResource(R.string.export_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.export_directory), "Storage", "settings/storage"),
                Triple(stringResource(R.string.general), "Content", "settings/content"),
                Triple(stringResource(R.string.hide_explicit), "Content", "settings/content"),
                Triple(stringResource(R.string.history_duration), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.image_cache), "Storage", "settings/storage"),
                Triple(stringResource(R.string.login), "Account", "settings/account"),
                Triple(stringResource(R.string.logout_clear_data), "Account", "settings/account"),
                Triple(stringResource(R.string.logout_dialog_message), "Account", "settings/account"),
                Triple(stringResource(R.string.logout_dialog_title), "Account", "settings/account"),
                Triple(stringResource(R.string.logout_keep_data), "Account", "settings/account"),
                Triple(stringResource(R.string.lyrics), "Content", "settings/content"),
                Triple(stringResource(R.string.max_image_cache_size), "Storage", "settings/storage"),
                Triple(stringResource(R.string.max_song_cache_size), "Storage", "settings/storage"),
                Triple(stringResource(R.string.misc), "Content", "settings/content"),
                Triple(stringResource(R.string.misc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.more_content), "Account", "settings/account"),
                Triple(stringResource(R.string.not_set), "Storage", "settings/storage"),
                Triple(stringResource(R.string.queue), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.quick_picks), "Content", "settings/content"),
                Triple(stringResource(R.string.randomize_home_order), "Content", "settings/content"),
                Triple(stringResource(R.string.randomize_home_order_desc), "Content", "settings/content"),
                Triple(stringResource(R.string.save), "Content", "settings/content"),
                Triple(stringResource(R.string.set_quick_picks), "Content", "settings/content"),
                Triple(stringResource(R.string.settings_section_player_content), "Account", "settings/account"),
                Triple(stringResource(R.string.show_album_canvas), "Content", "settings/content"),
                Triple(stringResource(R.string.show_album_canvas_desc), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_background_video), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_background_video_desc), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_description), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_monthly_listeners), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_subscriber_count), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_video), "Content", "settings/content"),
                Triple(stringResource(R.string.show_artist_video_desc), "Content", "settings/content"),
                Triple(stringResource(R.string.skip_silence), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.skip_silence_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.skip_silence_instant), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.skip_silence_instant_desc), "Player and audio", "settings/player"),
                Triple(stringResource(R.string.song_cache), "Storage", "settings/storage"),
                Triple(stringResource(R.string.storage), "Storage", "settings/storage"),
                Triple(stringResource(R.string.system_default), "Content", "settings/content"),
                Triple(stringResource(R.string.theme), "Appearance", "settings/appearance"),
                Triple(stringResource(R.string.theme_desc), "Appearance", "settings/appearance"),
                Triple(stringResource(R.string.token_adv_login_description), "Account", "settings/account"),
                Triple(stringResource(R.string.token_hidden), "Account", "settings/account"),
                Triple(stringResource(R.string.token_shown), "Account", "settings/account"),
                Triple(stringResource(R.string.top_length), "Content", "settings/content"),
                Triple(stringResource(R.string.yt_sync), "Account", "settings/account"),

                // Hardcoded Settings Missed by Generator
                Triple("Import from Spotify", "Backup & Restore", "settings/spotify_import"),
                Triple("Import from local file", "Backup & Restore", "settings/backup_restore"),
                Triple("Import 'm3u' Playlist", "Backup & Restore", "settings/backup_restore"),
                Triple("Import 'csv' Playlist", "Backup & Restore", "settings/backup_restore"),
                Triple("Local Backup", "Backup & Restore", "settings/backup_restore"),
                Triple("Integrations", "Settings", "settings/account"),
                Triple("Suggestions Region", "Content", "settings/content"),
                Triple("Speed Dial", "Content", "settings/content"),
                Triple("Import", "Backup & Restore", "settings/backup_restore"),
                Triple("Supported Links", "Settings", "settings"),
        )
}
