android.useAndroidX=true
android.newDsl=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4g


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key


org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
kotlin.incremental=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
